import 'dart:async';

import 'package:e_shopping/data/model/all_orders_model.dart';
import 'package:geolocator/geolocator.dart';
import 'package:get/get.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

import '../core/classes/status_request.dart';
import '../core/functions/handling_data.dart';
import '../core/services/my_services.dart';
import '../data/datasource/remote/cart/all_orders_data.dart';
import '../data/model/order_details.dart';

abstract class DetailsController extends GetxController {}

class DetailsControllerImp extends DetailsController {
  late AllOrderModel orderModel;
  Completer<GoogleMapController>? controllerMap;
  Position? position;
  StatusRequest statusRequest = StatusRequest.none;
  CameraPosition? kGooglePlex;
  List<Marker> markers = [];
  MyServices myServices = Get.find();
  AllOrdersData allOrdersData = AllOrdersData(Get.find());
  List<Autogenerated> data = [];

  getData() async {
    statusRequest = StatusRequest.loading;
    update();
    var response = await allOrdersData.allOrderdData(
      myServices.sharedPreferences.getInt("id").toString(),
    );
    statusRequest = handlingData(response);
    if (StatusRequest.success == statusRequest) {
      if (response["status"] == "success") {
        data.clear();
        List d = response["data"];
        data.addAll(d.map((e) => Autogenerated.fromJson(e)));
      } else {
        statusRequest = StatusRequest.failure;
      }
    }
    update();
  }

  initialData() {
    kGooglePlex = CameraPosition(
      target: LatLng(orderModel.lat!.toDouble(), orderModel.lon!.toDouble()),
      zoom: 50,
    );
    markers.add(Marker(
      markerId: MarkerId("1"),
      position: LatLng(orderModel.lat!.toDouble(), orderModel.lon!.toDouble()),
    ));
  }

  @override
  void onInit() {
    orderModel = Get.arguments["order"];
    initialData();
    super.onInit();
  }
}
